export const actions = {
    CHANGE_STATE: Symbol('CHANGE_STATE'),

    LOAD_WORDS: Symbol('LOAD_WORDS'),
    LOAD_WORDS_SUCCESS: Symbol('LOAD_WORDS_SUCCESS'),

    WORDS_OPERATE_CHANGED: Symbol('WORDS_OPERATE_CHANGED'),
    CHECKED_WORD: Symbol('CHECKED_WORD'),

    POST_WORD: Symbol('POST_WORD'),
    POST_WORD_SUCCESS: Symbol('POST_WORD_SUCCESS'),
    POST_WORD_FAIL: Symbol('POST_WORD_FAIL'),

    UPDATE_WORD: Symbol('UPDATE_WORD'),
    UPDATE_WORD_SUCCESS: Symbol('UPDATE_WORD_SUCCESS'),

    EXPAND_WORD: Symbol('EXPAND_WORD'),
    LOAD_EXPAND_WORD: Symbol('LOAD_EXPAND_WORD'),

    DELETE_WORDS: Symbol('DELETE_WORDS'),
    DELETE_WORDS_SUCCESS: Symbol('DELETE_WORDS_SUCCESS'),
    MARK_WORD: Symbol('MARK_WORD'),
}
